// <auto-generated />
using System;
using FitCoachPro.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitCoachPro.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250913175713_DataSeed")]
    partial class DataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitCoachPro.Domain.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GifUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            ExerciseName = "Push-ups",
                            GifUrl = "https://example.com/gifs/pushups.gif"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-222222222222"),
                            ExerciseName = "Squats",
                            GifUrl = "https://example.com/gifs/squats.gif"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-3333-3333-3333-333333333333"),
                            ExerciseName = "Plank",
                            GifUrl = "https://example.com/gifs/plank.gif"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-4444-4444-4444-444444444444"),
                            ExerciseName = "Lunges",
                            GifUrl = "https://example.com/gifs/lunges.gif"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-5555-5555-5555-555555555555"),
                            ExerciseName = "Pull-ups",
                            GifUrl = "https://example.com/gifs/pullups.gif"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-6666-6666-6666-666666666666"),
                            ExerciseName = "Deadlifts",
                            GifUrl = "https://example.com/gifs/deadlifts.gif"
                        });
                });

            modelBuilder.Entity("FitCoachPro.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfExpiredSubscription")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfRegistration")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("TelephoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            DateOfRegistration = new DateTime(2025, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            LastName = "Doe",
                            PasswordHash = "hash1",
                            Role = 0,
                            TelephoneNumber = "+123456789"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            DateOfRegistration = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Anna",
                            LastName = "Smith",
                            PasswordHash = "hash2",
                            Role = 0,
                            TelephoneNumber = "+987654321"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            DateOfRegistration = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mike",
                            LastName = "Johnson",
                            PasswordHash = "hash3",
                            Role = 0,
                            TelephoneNumber = "+192837465"
                        });
                });

            modelBuilder.Entity("FitCoachPro.Domain.Entities.WorkoutItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkoutPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("WorkoutItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaa1111-0000-0000-0000-000000000001"),
                            Description = "3 sets of 15 reps",
                            ExerciseId = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            WorkoutPlanId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aaaa1111-0000-0000-0000-000000000002"),
                            Description = "3 sets of 20 reps",
                            ExerciseId = new Guid("bbbbbbbb-2222-2222-2222-222222222222"),
                            WorkoutPlanId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("bbbb2222-0000-0000-0000-000000000001"),
                            Description = "Hold for 60 seconds",
                            ExerciseId = new Guid("cccccccc-3333-3333-3333-333333333333"),
                            WorkoutPlanId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("bbbb2222-0000-0000-0000-000000000002"),
                            Description = "3 sets of 10 reps per leg",
                            ExerciseId = new Guid("dddddddd-4444-4444-4444-444444444444"),
                            WorkoutPlanId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("cccc3333-0000-0000-0000-000000000001"),
                            Description = "3 sets to failure",
                            ExerciseId = new Guid("eeeeeeee-5555-5555-5555-555555555555"),
                            WorkoutPlanId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("cccc3333-0000-0000-0000-000000000002"),
                            Description = "3 sets of 8 reps",
                            ExerciseId = new Guid("ffffffff-6666-6666-6666-666666666666"),
                            WorkoutPlanId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("FitCoachPro.Domain.Entities.WorkoutPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfDoing")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutPlans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DateOfDoing = new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            DateOfDoing = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            DateOfDoing = new DateTime(2025, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        });
                });

            modelBuilder.Entity("FitCoachPro.Domain.Entities.WorkoutItem", b =>
                {
                    b.HasOne("FitCoachPro.Domain.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitCoachPro.Domain.Entities.WorkoutPlan", "WorkoutPlan")
                        .WithMany("WorkoutItems")
                        .HasForeignKey("WorkoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("FitCoachPro.Domain.Entities.WorkoutPlan", b =>
                {
                    b.HasOne("FitCoachPro.Domain.Entities.User", "User")
                        .WithMany("WorkoutPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCoachPro.Domain.Entities.User", b =>
                {
                    b.Navigation("WorkoutPlans");
                });

            modelBuilder.Entity("FitCoachPro.Domain.Entities.WorkoutPlan", b =>
                {
                    b.Navigation("WorkoutItems");
                });
#pragma warning restore 612, 618
        }
    }
}
