// <auto-generated />
using System;
using FitCoachPro.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitCoachPro.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250914153829_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitCoachPro.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfRegistration")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("TelephoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<int>("Role");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FitCoachPro.Domain.Entities.Workouts.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GifUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("FitCoachPro.Domain.Entities.Workouts.TemplateWorkoutItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("TemplateWorkoutItems");
                });

            modelBuilder.Entity("FitCoachPro.Domain.Entities.Workouts.WorkoutItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkoutPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("WorkoutItems");
                });

            modelBuilder.Entity("FitCoachPro.Domain.Entities.Workouts.WorkoutPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfDoing")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("WorkoutPlans");
                });

            modelBuilder.Entity("FitCoachPro.Domain.Entities.Users.Admin", b =>
                {
                    b.HasBaseType("FitCoachPro.Domain.Entities.Users.User");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("FitCoachPro.Domain.Entities.Users.Client", b =>
                {
                    b.HasBaseType("FitCoachPro.Domain.Entities.Users.User");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfExpiredSubscription")
                        .HasColumnType("datetime2");

                    b.HasIndex("CoachId");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("FitCoachPro.Domain.Entities.Users.Coach", b =>
                {
                    b.HasBaseType("FitCoachPro.Domain.Entities.Users.User");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("FitCoachPro.Domain.Entities.Workouts.TemplateWorkoutItem", b =>
                {
                    b.HasOne("FitCoachPro.Domain.Entities.Users.Coach", "Coach")
                        .WithMany("TemplateWorkoutItems")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitCoachPro.Domain.Entities.Workouts.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("FitCoachPro.Domain.Entities.Workouts.WorkoutItem", b =>
                {
                    b.HasOne("FitCoachPro.Domain.Entities.Workouts.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitCoachPro.Domain.Entities.Workouts.WorkoutPlan", "WorkoutPlan")
                        .WithMany("WorkoutItems")
                        .HasForeignKey("WorkoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("FitCoachPro.Domain.Entities.Workouts.WorkoutPlan", b =>
                {
                    b.HasOne("FitCoachPro.Domain.Entities.Users.Client", "Client")
                        .WithMany("WorkoutPlans")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("FitCoachPro.Domain.Entities.Users.Client", b =>
                {
                    b.HasOne("FitCoachPro.Domain.Entities.Users.Coach", "Coach")
                        .WithMany("Clients")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("FitCoachPro.Domain.Entities.Workouts.WorkoutPlan", b =>
                {
                    b.Navigation("WorkoutItems");
                });

            modelBuilder.Entity("FitCoachPro.Domain.Entities.Users.Client", b =>
                {
                    b.Navigation("WorkoutPlans");
                });

            modelBuilder.Entity("FitCoachPro.Domain.Entities.Users.Coach", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("TemplateWorkoutItems");
                });
#pragma warning restore 612, 618
        }
    }
}
