using FitCoachPro.Application.Common.Models.Workouts.TemplateWorkoutPlan;

namespace FitCoachPro.Application.Commands.TemplateWorkoutPlans.CreateTemplateWorkoutPlan;

public record CreateTemplateCommand(CreateTemplateWorkoutPlanModel Model);
